import {Menu} from './menu.model';


export const verticalMenuItems = [
    /*new Menu(1, TraductionService.lang.translate.instant('APPS.CONTENT_HEADERS.TABLEAU_DE_BORD.TITLE'),
        '/re-tableau-de-bord', null, 'dashboard', null, false, 0),*/
    new Menu(2, 'Placement en Facultative', '/re-placement-en-fac', null, 'folder', null, false, 0),
    new Menu(3, 'Sinistre', '/re-sinistre', null, 'error', null, false, 0),
    new Menu(4, 'Mouvement de Trésorerie', '/re-mouvement-de-tresorerie', null, 'attach_money', null, true, 0),
    new Menu(41, 'Encaissement', '/re-encaissement', null, 'attach_money', null, false, 4),
    new Menu(41, 'Décaissement', '/re-decaissement', null, 'attach_money', null, false, 4),
    new Menu(5, 'Echanges', '/re-echanges', null, 'swap_vert', null, false, 0),
    new Menu(6, 'Paramètres', '/re-parametrage', null, 'build', null, true, 0),
    new Menu(61, 'Paramètres de base', '/re-parametrage-de-base', null, 'build', null, false, 6),
    new Menu(62, 'Paramètres métier', '/re-parametrage-metier', null, 'build', null, false, 6),
    new Menu(7, 'Administration', '/re-administration', null, 'account_circle', null, false, 0),
];

export const horizontalMenuItems = [
    new Menu(1, 'Dashboard', '/', null, 'dashboard', null, false, 0),
    new Menu(300, 'Mon Espace', null, null, 'person', null, true, 0),
    new Menu(301, 'Vue Générale', '/sgi-vue-generale', null, 'person', null, false, 300),
    new Menu(302, 'Mon Portefeuille', '/sgi-mon-portefeuille', null, 'person', null, false, 300),
    new Menu(303, 'Opérations', null, null, 'ballot', null, true, 0),
    new Menu(304, 'Mes Mouvements', '/sgi-mes-mouvements', null, 'ballot', null, false, 303),
    new Menu(305, 'Mes Virements', '/sgi-mes-virements', null, 'ballot', null, false, 303),
    new Menu(306, 'Mes Ordres', '/sgi-mes-ordres', null, 'ballot', null, false, 303),
    new Menu(307, 'Mes Souscriptions', '/sgi-mes-souscriptions', null, 'ballot', null, false, 303),
    new Menu(308, 'Mes Transactions', '/sgi-mes-transactions', null, 'ballot', null, false, 303),
    new Menu(309, 'Mes Simulations', '/sgi-mes-simulations', null, 'ballot', null, false, 303),
    new Menu(310, 'Cours de Bourse', '/sgi-cours-bourse', null, 'access_time', null, false, 0),
    new Menu(311, 'Administration', null, null, 'build', null, true, 0),
    new Menu(312, 'Compte Utilisateur', '/sgi-compte-utilisateur',
        null, 'person', null, false, 311), new Menu(313, 'Paramètres', '/sgi-parametres', null, 'settings', null, false, 311),
    new Menu(314, 'Synchronisation', '/sgi-identification', null, 'sync', null, false, 311),
    new Menu(315, 'Synchronisation', '/sgi-synchronisation', null, 'sync', null, false, 0),
    new Menu(2, 'Users', '/users', null, 'supervisor_account', null, false, 0),
    new Menu(3, 'UI Features', null, null, 'computer', null, true, 0),
    new Menu(4, 'Buttons', '/ui/buttons', null, 'keyboard', null, false, 3),
    new Menu(5, 'Cards', '/ui/cards', null, 'card_membership', null, false, 3),
    new Menu(6, 'Lists', '/ui/lists', null, 'list', null, false, 3),
    new Menu(7, 'Grids', '/ui/grids', null, 'grid_on', null, false, 3),
    new Menu(8, 'Tabs', '/ui/tabs', null, 'tab', null, false, 3),
    new Menu(9, 'Expansion Panel', '/ui/expansion-panel', null, 'dns', null, false, 3),
    new Menu(10, 'Chips', '/ui/chips', null, 'label', null, false, 3),
    new Menu(11, 'Progress', '/ui/progress', null, 'data_usage', null, false, 3),
    new Menu(12, 'Dialog', '/ui/dialog', null, 'open_in_new', null, false, 3),
    new Menu(13, 'Tooltip', '/ui/tooltip', null, 'chat_bubble', null, false, 3),
    new Menu(14, 'Snackbar', '/ui/snack-bar', null, 'sms', null, false, 3),
    new Menu(16, 'Mailbox', '/mailbox', null, 'email', null, false, 40),
    new Menu(17, 'Chat', '/chat', null, 'chat', null, false, 40),
    new Menu(20, 'Form Controls', null, null, 'dvr', null, true, 0),
    new Menu(21, 'Autocomplete', '/form-controls/autocomplete', null, 'short_text', null, false, 20),
    new Menu(22, 'Checkbox', '/form-controls/checkbox', null, 'check_box', null, false, 20),
    new Menu(23, 'Datepicker', '/form-controls/datepicker', null, 'today', null, false, 20),
    new Menu(24, 'Form field', '/form-controls/form-field', null, 'view_stream', null, false, 20),
    new Menu(25, 'Input', '/form-controls/input', null, 'input', null, false, 20),
    new Menu(26, 'Radio button', '/form-controls/radio-button', null, 'radio_button_checked', null, false, 20),
    new Menu(27, 'Select', '/form-controls/select', null, 'playlist_add_check', null, false, 20),
    new Menu(28, 'Slider', '/form-controls/slider', null, 'tune', null, false, 20),
    new Menu(29, 'Slide toggle', '/form-controls/slide-toggle', null, 'star_half', null, false, 20),
    new Menu(30, 'Tables', null, null, 'view_module', null, true, 0),
    new Menu(31, 'Basic', '/tables/basic', null, 'view_column', null, false, 30),
    new Menu(32, 'Paging', '/tables/paging', null, 'last_page', null, false, 30),
    new Menu(33, 'Sorting', '/tables/sorting', null, 'sort', null, false, 30),
    new Menu(34, 'Filtering', '/tables/filtering', null, 'format_line_spacing', null, false, 30),
    new Menu(35, 'Selecting', '/tables/selecting', null, 'playlist_add_check', null, false, 30),
    new Menu(36, 'NGX DataTable', '/tables/ngx-table', null, 'view_array', null, false, 30),
    new Menu(70, 'Charts', null, null, 'multiline_chart', null, true, 0),
    new Menu(71, 'Bar Charts', '/charts/bar', null, 'insert_chart', null, false, 70),
    new Menu(72, 'Pie Charts', '/charts/pie', null, 'pie_chart', null, false, 70),
    new Menu(73, 'Line Charts', '/charts/line', null, 'show_chart', null, false, 70),
    new Menu(74, 'Bubble Charts', '/charts/bubble', null, 'bubble_chart', null, false, 70),
    new Menu(81, 'Drag & Drop', '/drag-drop', null, 'mouse', null, false, 3),
    new Menu(85, 'Material Icons', '/icons', null, 'insert_emoticon', null, false, 3),
    new Menu(40, 'Pages', null, null, 'library_books', null, true, 0),
    new Menu(43, 'Login', '/login', null, 'exit_to_app', null, false, 40),
    new Menu(44, 'Register', '/register', null, 'person_add', null, false, 40),
    new Menu(45, 'Blank', '/blank', null, 'check_box_outline_blank', null, false, 40),
    new Menu(46, 'Page Not Found', '/pagenotfound', null, 'error_outline', null, false, 40),
    new Menu(47, 'Error', '/error', null, 'warning', null, false, 40),
    new Menu(48, 'Search', '/search', null, 'search', null, false, 40),
    new Menu(49, 'Landing', '/landing', null, 'filter', null, false, 40),
    new Menu(50, 'Schedule', '/schedule', null, 'event_note', null, false, 40),
    new Menu(200, 'External Link', null, 'http://themeseason.com', 'open_in_new', '_blank', false, 40),
    new Menu(66, 'Maps', null, null, 'map', null, true, 0),
    new Menu(67, 'Google', '/maps/googlemaps', null, 'location_on', null, false, 66),
    new Menu(68, 'Leaflet', '/maps/leafletmaps', null, 'my_location', null, false, 66),
];

export const verticalMenuItemsEnglish = [
    new Menu(1, 'Dashborad', '/re-tableau-de-bord', null, 'dashboard', null, false, 0),
    new Menu(2, 'Optional Placement', '/re-placement-en-fac', null, 'folder', null, false, 0),
    new Menu(3, 'Sinister', '/re-sinistre', null, 'error', null, false, 0),
    new Menu(4, 'Cashflow', '/re-mouvement-de-tresorerie', null, 'attach_money', null, true, 0),
    new Menu(41, 'Incoming', '/re-encaissement', null, 'attach_money', null, false, 4),
    new Menu(41, 'Outgoing', '/re-decaissement', null, 'attach_money', null, false, 4),
    new Menu(5, 'Exchanges', '/re-echanges', null, 'swap_vert', null, false, 0),
    new Menu(6, 'Parameters', '/re-parametrage', null, 'build', null, true, 0),
    new Menu(61, 'Basic Parameters', '/re-parametrage-de-base', null, 'build', null, false, 6),
    new Menu(62, 'Specific Parameters ', '/re-parametrage-metier', null, 'build', null, false, 6),
    new Menu(7, 'Administration', '/re-administration', null, 'account_circle', null, false, 0),
];